services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: git-diff-notes-generator-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_DEV_PASSWORD}
    ports:
      - "5432:5432"
  rabbitmq-broker:
    image: 'rabbitmq:3-management-alpine'
    environment:
      - 'RABBITMQ_DEFAULT_USER=myuser'
      - 'RABBITMQ_DEFAULT_PASS=mypassword'
    ports:
      - '5672:5672'
      - '15672:15672'