spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/git-diff-notes-generator-database
    username: postgres
    password: ${DATABASE_DEV_PASSWORD}
    driver-class-name: org.postgresql.Driver
  ai:
    ollama:
      chat:
        model: qwen3:8b
        temperature: 0.3
        think: false
  jpa:
    show-sql: true