spring:
  application:
    name: automated-git-diff-notes-generator
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
github:
  api:
    token: ${GITHUB_PAT_TOKEN}
  webhook:
    secret: ${WEBHOOK_SECRET}